[package]
name = "ch2-web"
version = "0.1.0"
edition = "2021"
# Do not publish to crates.io
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.5"
