[package]
name = "ch3-web"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.5"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["json"] }
headers = "0.4.0"
axum-macros = "0.4.1"
